spring:
  application:
    name: product
  data:
    mongodb.database: masterdb
  activemq:
    broker-url: tcp://localhost:61616
  jms:
    pub-sub-domain: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5

jms:
  ProductTopic: ProductT