spring:
  application:
    name: product
  data:
    mongodb.database: masterdb

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5

env: dev