spring:
  application:
    name: product

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8081

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5

env: dev

logging:
  level:
    org.hibernate:
      tool.hbm2ddl: DEBUG
      SQL: DEBUG