spring:
  application:
    name: product
  data:
    elasticsearch:
      repositories.enabled: true
      cluster-name: elasticsearch_siprianus
      cluster-nodes: localhost:9300

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8085

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5

env: dev