spring:
  application:
    name: product
  activemq:
    broker-url: tcp://localhost:61616
  data:
    elasticsearch:
      repositories.enabled: true
      cluster-name: elasticsearch_siprianus
      cluster-nodes: localhost:9300
  jms:
    pub-sub-domain: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8086

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5

env: dev

jms:
  ProductTopic: ProductT